/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "app.h"
#include "RTC.h"


extern char buffer[100];

extern char buffer1[100];

RTC_InitDefaultTypeDef DefaultValue = {27, 4, 2025, 0, 23, 57, 59};


int main(void)
{
    Init_LCD();
    RTC_Init(&DefaultValue);
    while(1)
    {
        GetValueDisplay_RTC();
        Delay(3);
        lcd_gotoxy(0, 0);
        lcd_puts(buffer);
        lcd_gotoxy(0, 1);
        lcd_puts(buffer1);
    }
}
